# Generated by Django 3.1.7 on 2021-03-25 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListCertification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='nom')),
            ],
            options={
                'verbose_name': 'Certification',
            },
        ),
        migrations.CreateModel(
            name='ListWorkStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='nom')),
                ('commentary', models.CharField(max_length=250, verbose_name='commentaire')),
            ],
            options={
                'verbose_name': 'Liste postes de travail',
            },
        ),
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Société',
            },
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Extern', models.BooleanField(default=False, verbose_name="Externe à l'entreprise?")),
                ('certification', models.ManyToManyField(blank=True, related_name='collaboraters', to='app_matrice.ListCertification')),
                ('society', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_matrice.society', verbose_name='Société')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur ')),
                ('workstation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_matrice.listworkstation', verbose_name='Poste de travail')),
            ],
            options={
                'verbose_name': 'Profil',
            },
        ),
        migrations.CreateModel(
            name='Collaborater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collaborater', models.BooleanField(default=True, verbose_name='Etes-vous un collaborateur ?')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur ')),
            ],
            options={
                'verbose_name': 'Collaborateur',
            },
        ),
    ]
