# Generated by Django 3.1.7 on 2021-03-26 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_matrice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='nom')),
                ('description', models.CharField(max_length=250, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Domaine',
            },
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nom')),
                ('commentary', models.CharField(max_length=250, verbose_name='commentaire')),
                ('field', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_matrice.field')),
            ],
            options={
                'verbose_name': 'Compétence',
            },
        ),
    ]
