# Generated by Django 3.1.7 on 2021-03-26 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_matrice', '0004_auto_20210326_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='society',
            name='user',
        ),
        migrations.AddField(
            model_name='profil',
            name='society',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_matrice.society', verbose_name='Société'),
        ),
    ]
