# Generated by Django 3.1.7 on 2021-04-01 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_matrice', '0006_auto_20210331_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=10, unique=True, verbose_name='valeur')),
                ('commentary', models.CharField(max_length=250, verbose_name='commentaire')),
            ],
            options={
                'verbose_name': 'Liste des intérêt',
            },
        ),
        migrations.CreateModel(
            name='ListLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=10, unique=True, verbose_name='valeur')),
                ('commentary', models.CharField(max_length=250, verbose_name='commentaire')),
            ],
            options={
                'verbose_name': 'Liste des niveaux',
            },
        ),
        migrations.CreateModel(
            name='ListofCompetence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Level', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='0', max_length=20)),
                ('Interest', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='0', max_length=20)),
                ('Competence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_matrice.competence', verbose_name='Compétence')),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Competences des utilisateur',
            },
        ),
    ]
