# Generated by Django 3.1.7 on 2021-04-01 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_matrice', '0007_listinterest_listlevel_listofcompetence'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListInterest',
        ),
        migrations.DeleteModel(
            name='ListLevel',
        ),
    ]
