# Generated by Django 3.1.7 on 2021-04-08 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_matrice', '0013_remove_society_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('society', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_matrice.society', verbose_name='Société')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur ')),
            ],
            options={
                'verbose_name': 'Profil_utilisateur',
            },
        ),
    ]
